### ISSUE TITLE
Files generated by antlr4 not uploaded

### ISSUE THREAD

**Issue by tlzhao-casia** [enlite-ai/maze-l2rpn-2022-submission#2]
Hi:
    Thank you very much for sharing the excellent agent for power grid dispaching. However, when I try to run the submitted codes, there is an error saying that the agent is failed to load the parser. The error log is as follows:

**Error importing generated parsers, run `python setup.py antlr` to regenerate.**

I checked the codes carefully and found that the files generated by antlr4 (the two files OverrideLexer.py and OverrideParser.py), which should have been in the directory _hydra/grammar/gen_, are not included in the uploaded codes. Could you please upload the required files so that I can run the codes and have a more comprehensive understanding to your excellent work?

Thanks!

**Comment by tlzhao-casia** [comment]
I have resolved the problem and re-produced the good results. Thanks.

**Comment by md-enlite** [comment]
Perfect!

**Comment by HHYHRHY** [comment]
> I have resolved the problem and re-produced the good results. Thanks.

Hello,May I ask the way to solve this problem? I have the same error! Thanks!!
